/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TentangRouteImport } from './routes/tentang'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DaftarAnggotaRouteImport } from './routes/daftar-anggota'
import { Route as BeritaRouteImport } from './routes/berita'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MarketplaceIndexRouteImport } from './routes/marketplace.index'
import { Route as BeritaIndexRouteImport } from './routes/berita.index'
import { Route as MarketplaceKeranjangRouteImport } from './routes/marketplace.keranjang'
import { Route as MarketplaceCheckoutRouteImport } from './routes/marketplace.checkout'
import { Route as BeritaSlugRouteImport } from './routes/berita.$slug'
import { Route as AuthenticatedVotingRouteImport } from './routes/_authenticated/voting'
import { Route as AuthenticatedTransaksiSayaRouteImport } from './routes/_authenticated/transaksi-saya'
import { Route as AuthenticatedTabunganBerjangkaRouteImport } from './routes/_authenticated/tabungan-berjangka'
import { Route as AuthenticatedSurveiRouteImport } from './routes/_authenticated/survei'
import { Route as AuthenticatedSimpananRouteImport } from './routes/_authenticated/simpanan'
import { Route as AuthenticatedShuRouteImport } from './routes/_authenticated/shu'
import { Route as AuthenticatedSaldoRouteImport } from './routes/_authenticated/saldo'
import { Route as AuthenticatedRiwayatRouteImport } from './routes/_authenticated/riwayat'
import { Route as AuthenticatedRapatRouteImport } from './routes/_authenticated/rapat'
import { Route as AuthenticatedProfilRouteImport } from './routes/_authenticated/profil'
import { Route as AuthenticatedPinjamanRouteImport } from './routes/_authenticated/pinjaman'
import { Route as AuthenticatedPenjaminRouteImport } from './routes/_authenticated/penjamin'
import { Route as AuthenticatedMarketplaceSayaRouteImport } from './routes/_authenticated/marketplace-saya'
import { Route as AuthenticatedLowonganRouteImport } from './routes/_authenticated/lowongan'
import { Route as AuthenticatedKalkulatorRouteImport } from './routes/_authenticated/kalkulator'
import { Route as AuthenticatedFavoritRouteImport } from './routes/_authenticated/favorit'
import { Route as AuthenticatedDokumenRouteImport } from './routes/_authenticated/dokumen'
import { Route as AuthenticatedDashboardBelanjaRouteImport } from './routes/_authenticated/dashboard-belanja'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedBukuBesarRouteImport } from './routes/_authenticated/buku-besar'
import { Route as AuthenticatedBantuanRouteImport } from './routes/_authenticated/bantuan'
import { Route as AuthenticatedApprovalRouteImport } from './routes/_authenticated/approval'
import { Route as AuthenticatedAngsuranRouteImport } from './routes/_authenticated/angsuran'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as VerifyRouteImport } from './routes/verify.'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as MarketplaceTokoSlugRouteImport } from './routes/marketplace.toko.$slug'
import { Route as MarketplaceProdukIdRouteImport } from './routes/marketplace.produk.$id'
import { Route as AuthenticatedSekolahPengadaanRouteImport } from './routes/_authenticated/sekolah.pengadaan'
import { Route as AuthenticatedGerejaPengadaanRouteImport } from './routes/_authenticated/gereja.pengadaan'
import { Route as AuthenticatedAdminVotingRouteImport } from './routes/_authenticated/admin.voting'
import { Route as AuthenticatedAdminVerifikasiPinjamanRouteImport } from './routes/_authenticated/admin.verifikasi-pinjaman'
import { Route as AuthenticatedAdminTabunganBerjangkaRouteImport } from './routes/_authenticated/admin.tabungan-berjangka'
import { Route as AuthenticatedAdminSurveiRouteImport } from './routes/_authenticated/admin.survei'
import { Route as AuthenticatedAdminSuratRouteImport } from './routes/_authenticated/admin.surat'
import { Route as AuthenticatedAdminSupportRouteImport } from './routes/_authenticated/admin.support'
import { Route as AuthenticatedAdminStatistikRouteImport } from './routes/_authenticated/admin.statistik'
import { Route as AuthenticatedAdminSimpananRouteImport } from './routes/_authenticated/admin.simpanan'
import { Route as AuthenticatedAdminShuRouteImport } from './routes/_authenticated/admin.shu'
import { Route as AuthenticatedAdminSellerVerifyRouteImport } from './routes/_authenticated/admin.seller-verify'
import { Route as AuthenticatedAdminRoleRouteImport } from './routes/_authenticated/admin.role'
import { Route as AuthenticatedAdminRekonsiliasiRouteImport } from './routes/_authenticated/admin.rekonsiliasi'
import { Route as AuthenticatedAdminRapbRouteImport } from './routes/_authenticated/admin.rapb'
import { Route as AuthenticatedAdminQrisRouteImport } from './routes/_authenticated/admin.qris'
import { Route as AuthenticatedAdminPinjamanRouteImport } from './routes/_authenticated/admin.pinjaman'
import { Route as AuthenticatedAdminPenjaminRouteImport } from './routes/_authenticated/admin.penjamin'
import { Route as AuthenticatedAdminPengaturanRouteImport } from './routes/_authenticated/admin.pengaturan'
import { Route as AuthenticatedAdminPenagihanRouteImport } from './routes/_authenticated/admin.penagihan'
import { Route as AuthenticatedAdminOpexRouteImport } from './routes/_authenticated/admin.opex'
import { Route as AuthenticatedAdminNotifikasiWaRouteImport } from './routes/_authenticated/admin.notifikasi-wa'
import { Route as AuthenticatedAdminMarketplaceRouteImport } from './routes/_authenticated/admin.marketplace'
import { Route as AuthenticatedAdminLowonganRouteImport } from './routes/_authenticated/admin.lowongan'
import { Route as AuthenticatedAdminLaporanSakRouteImport } from './routes/_authenticated/admin.laporan-sak'
import { Route as AuthenticatedAdminLaporanRatRouteImport } from './routes/_authenticated/admin.laporan-rat'
import { Route as AuthenticatedAdminLaporanRouteImport } from './routes/_authenticated/admin.laporan'
import { Route as AuthenticatedAdminKuponRouteImport } from './routes/_authenticated/admin.kupon'
import { Route as AuthenticatedAdminKomplainRouteImport } from './routes/_authenticated/admin.komplain'
import { Route as AuthenticatedAdminFeeRouteImport } from './routes/_authenticated/admin.fee'
import { Route as AuthenticatedAdminEscrowRouteImport } from './routes/_authenticated/admin.escrow'
import { Route as AuthenticatedAdminDanaCadanganRouteImport } from './routes/_authenticated/admin.dana-cadangan'
import { Route as AuthenticatedAdminBukuKasRouteImport } from './routes/_authenticated/admin.buku-kas'
import { Route as AuthenticatedAdminBukuBesarRouteImport } from './routes/_authenticated/admin.buku-besar'
import { Route as AuthenticatedAdminBeritaRouteImport } from './routes/_authenticated/admin.berita'
import { Route as AuthenticatedAdminBackupRouteImport } from './routes/_authenticated/admin.backup'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated/admin.audit'
import { Route as AuthenticatedAdminAsetRouteImport } from './routes/_authenticated/admin.aset'
import { Route as AuthenticatedAdminArsipTransaksiRouteImport } from './routes/_authenticated/admin.arsip-transaksi'
import { Route as AuthenticatedAdminApprovalRouteImport } from './routes/_authenticated/admin.approval'
import { Route as AuthenticatedAdminAngsuranRouteImport } from './routes/_authenticated/admin.angsuran'
import { Route as AuthenticatedAdminAnggotaRouteImport } from './routes/_authenticated/admin.anggota'
import { Route as AuthenticatedAdminAnalitikRouteImport } from './routes/_authenticated/admin.analitik'
import { Route as AuthenticatedAdminAktivitasRouteImport } from './routes/_authenticated/admin.aktivitas'
import { Route as AuthenticatedAdminAkadRouteImport } from './routes/_authenticated/admin.akad'
import { Route as ApiPublicHooksDailyRemindersRouteImport } from './routes/api/public/hooks/daily-reminders'
import { Route as ApiPublicHooksAutoReleaseEscrowRouteImport } from './routes/api/public/hooks/auto-release-escrow'
import { Route as ApiPublicHooksAutoDebetWajibRouteImport } from './routes/api/public/hooks/auto-debet-wajib'
import { Route as ApiPublicHooksAccrueFeesRouteImport } from './routes/api/public/hooks/accrue-fees'
import { Route as AuthenticatedSekolahPengadaanIdRouteImport } from './routes/_authenticated/sekolah.pengadaan.$id'
import { Route as AuthenticatedGerejaPengadaanIdRouteImport } from './routes/_authenticated/gereja.pengadaan.$id'
import { Route as AuthenticatedAdminSekolahPengadaanRouteImport } from './routes/_authenticated/admin.sekolah.pengadaan'
import { Route as AuthenticatedAdminGerejaPengadaanRouteImport } from './routes/_authenticated/admin.gereja.pengadaan'

const TentangRoute = TentangRouteImport.update({
  id: '/tentang',
  path: '/tentang',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DaftarAnggotaRoute = DaftarAnggotaRouteImport.update({
  id: '/daftar-anggota',
  path: '/daftar-anggota',
  getParentRoute: () => rootRouteImport,
} as any)
const BeritaRoute = BeritaRouteImport.update({
  id: '/berita',
  path: '/berita',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceIndexRoute = MarketplaceIndexRouteImport.update({
  id: '/marketplace/',
  path: '/marketplace/',
  getParentRoute: () => rootRouteImport,
} as any)
const BeritaIndexRoute = BeritaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BeritaRoute,
} as any)
const MarketplaceKeranjangRoute = MarketplaceKeranjangRouteImport.update({
  id: '/marketplace/keranjang',
  path: '/marketplace/keranjang',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceCheckoutRoute = MarketplaceCheckoutRouteImport.update({
  id: '/marketplace/checkout',
  path: '/marketplace/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const BeritaSlugRoute = BeritaSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BeritaRoute,
} as any)
const AuthenticatedVotingRoute = AuthenticatedVotingRouteImport.update({
  id: '/voting',
  path: '/voting',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTransaksiSayaRoute =
  AuthenticatedTransaksiSayaRouteImport.update({
    id: '/transaksi-saya',
    path: '/transaksi-saya',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTabunganBerjangkaRoute =
  AuthenticatedTabunganBerjangkaRouteImport.update({
    id: '/tabungan-berjangka',
    path: '/tabungan-berjangka',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSurveiRoute = AuthenticatedSurveiRouteImport.update({
  id: '/survei',
  path: '/survei',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSimpananRoute = AuthenticatedSimpananRouteImport.update({
  id: '/simpanan',
  path: '/simpanan',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedShuRoute = AuthenticatedShuRouteImport.update({
  id: '/shu',
  path: '/shu',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSaldoRoute = AuthenticatedSaldoRouteImport.update({
  id: '/saldo',
  path: '/saldo',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRiwayatRoute = AuthenticatedRiwayatRouteImport.update({
  id: '/riwayat',
  path: '/riwayat',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRapatRoute = AuthenticatedRapatRouteImport.update({
  id: '/rapat',
  path: '/rapat',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfilRoute = AuthenticatedProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPinjamanRoute = AuthenticatedPinjamanRouteImport.update({
  id: '/pinjaman',
  path: '/pinjaman',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPenjaminRoute = AuthenticatedPenjaminRouteImport.update({
  id: '/penjamin',
  path: '/penjamin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMarketplaceSayaRoute =
  AuthenticatedMarketplaceSayaRouteImport.update({
    id: '/marketplace-saya',
    path: '/marketplace-saya',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLowonganRoute = AuthenticatedLowonganRouteImport.update({
  id: '/lowongan',
  path: '/lowongan',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedKalkulatorRoute = AuthenticatedKalkulatorRouteImport.update({
  id: '/kalkulator',
  path: '/kalkulator',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFavoritRoute = AuthenticatedFavoritRouteImport.update({
  id: '/favorit',
  path: '/favorit',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDokumenRoute = AuthenticatedDokumenRouteImport.update({
  id: '/dokumen',
  path: '/dokumen',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardBelanjaRoute =
  AuthenticatedDashboardBelanjaRouteImport.update({
    id: '/dashboard-belanja',
    path: '/dashboard-belanja',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBukuBesarRoute = AuthenticatedBukuBesarRouteImport.update({
  id: '/buku-besar',
  path: '/buku-besar',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBantuanRoute = AuthenticatedBantuanRouteImport.update({
  id: '/bantuan',
  path: '/bantuan',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedApprovalRoute = AuthenticatedApprovalRouteImport.update({
  id: '/approval',
  path: '/approval',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAngsuranRoute = AuthenticatedAngsuranRouteImport.update({
  id: '/angsuran',
  path: '/angsuran',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify/',
  path: '/verify/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const MarketplaceTokoSlugRoute = MarketplaceTokoSlugRouteImport.update({
  id: '/marketplace/toko/$slug',
  path: '/marketplace/toko/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceProdukIdRoute = MarketplaceProdukIdRouteImport.update({
  id: '/marketplace/produk/$id',
  path: '/marketplace/produk/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSekolahPengadaanRoute =
  AuthenticatedSekolahPengadaanRouteImport.update({
    id: '/sekolah/pengadaan',
    path: '/sekolah/pengadaan',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGerejaPengadaanRoute =
  AuthenticatedGerejaPengadaanRouteImport.update({
    id: '/gereja/pengadaan',
    path: '/gereja/pengadaan',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminVotingRoute =
  AuthenticatedAdminVotingRouteImport.update({
    id: '/voting',
    path: '/voting',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminVerifikasiPinjamanRoute =
  AuthenticatedAdminVerifikasiPinjamanRouteImport.update({
    id: '/verifikasi-pinjaman',
    path: '/verifikasi-pinjaman',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTabunganBerjangkaRoute =
  AuthenticatedAdminTabunganBerjangkaRouteImport.update({
    id: '/tabungan-berjangka',
    path: '/tabungan-berjangka',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSurveiRoute =
  AuthenticatedAdminSurveiRouteImport.update({
    id: '/survei',
    path: '/survei',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSuratRoute = AuthenticatedAdminSuratRouteImport.update({
  id: '/surat',
  path: '/surat',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminSupportRoute =
  AuthenticatedAdminSupportRouteImport.update({
    id: '/support',
    path: '/support',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminStatistikRoute =
  AuthenticatedAdminStatistikRouteImport.update({
    id: '/statistik',
    path: '/statistik',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSimpananRoute =
  AuthenticatedAdminSimpananRouteImport.update({
    id: '/simpanan',
    path: '/simpanan',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminShuRoute = AuthenticatedAdminShuRouteImport.update({
  id: '/shu',
  path: '/shu',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminSellerVerifyRoute =
  AuthenticatedAdminSellerVerifyRouteImport.update({
    id: '/seller-verify',
    path: '/seller-verify',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRoleRoute = AuthenticatedAdminRoleRouteImport.update({
  id: '/role',
  path: '/role',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminRekonsiliasiRoute =
  AuthenticatedAdminRekonsiliasiRouteImport.update({
    id: '/rekonsiliasi',
    path: '/rekonsiliasi',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRapbRoute = AuthenticatedAdminRapbRouteImport.update({
  id: '/rapb',
  path: '/rapb',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminQrisRoute = AuthenticatedAdminQrisRouteImport.update({
  id: '/qris',
  path: '/qris',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminPinjamanRoute =
  AuthenticatedAdminPinjamanRouteImport.update({
    id: '/pinjaman',
    path: '/pinjaman',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPenjaminRoute =
  AuthenticatedAdminPenjaminRouteImport.update({
    id: '/penjamin',
    path: '/penjamin',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPengaturanRoute =
  AuthenticatedAdminPengaturanRouteImport.update({
    id: '/pengaturan',
    path: '/pengaturan',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPenagihanRoute =
  AuthenticatedAdminPenagihanRouteImport.update({
    id: '/penagihan',
    path: '/penagihan',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminOpexRoute = AuthenticatedAdminOpexRouteImport.update({
  id: '/opex',
  path: '/opex',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminNotifikasiWaRoute =
  AuthenticatedAdminNotifikasiWaRouteImport.update({
    id: '/notifikasi-wa',
    path: '/notifikasi-wa',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMarketplaceRoute =
  AuthenticatedAdminMarketplaceRouteImport.update({
    id: '/marketplace',
    path: '/marketplace',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminLowonganRoute =
  AuthenticatedAdminLowonganRouteImport.update({
    id: '/lowongan',
    path: '/lowongan',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminLaporanSakRoute =
  AuthenticatedAdminLaporanSakRouteImport.update({
    id: '/laporan-sak',
    path: '/laporan-sak',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminLaporanRatRoute =
  AuthenticatedAdminLaporanRatRouteImport.update({
    id: '/laporan-rat',
    path: '/laporan-rat',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminLaporanRoute =
  AuthenticatedAdminLaporanRouteImport.update({
    id: '/laporan',
    path: '/laporan',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminKuponRoute = AuthenticatedAdminKuponRouteImport.update({
  id: '/kupon',
  path: '/kupon',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminKomplainRoute =
  AuthenticatedAdminKomplainRouteImport.update({
    id: '/komplain',
    path: '/komplain',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFeeRoute = AuthenticatedAdminFeeRouteImport.update({
  id: '/fee',
  path: '/fee',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminEscrowRoute =
  AuthenticatedAdminEscrowRouteImport.update({
    id: '/escrow',
    path: '/escrow',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDanaCadanganRoute =
  AuthenticatedAdminDanaCadanganRouteImport.update({
    id: '/dana-cadangan',
    path: '/dana-cadangan',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBukuKasRoute =
  AuthenticatedAdminBukuKasRouteImport.update({
    id: '/buku-kas',
    path: '/buku-kas',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBukuBesarRoute =
  AuthenticatedAdminBukuBesarRouteImport.update({
    id: '/buku-besar',
    path: '/buku-besar',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBeritaRoute =
  AuthenticatedAdminBeritaRouteImport.update({
    id: '/berita',
    path: '/berita',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBackupRoute =
  AuthenticatedAdminBackupRouteImport.update({
    id: '/backup',
    path: '/backup',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAsetRoute = AuthenticatedAdminAsetRouteImport.update({
  id: '/aset',
  path: '/aset',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminArsipTransaksiRoute =
  AuthenticatedAdminArsipTransaksiRouteImport.update({
    id: '/arsip-transaksi',
    path: '/arsip-transaksi',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminApprovalRoute =
  AuthenticatedAdminApprovalRouteImport.update({
    id: '/approval',
    path: '/approval',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAngsuranRoute =
  AuthenticatedAdminAngsuranRouteImport.update({
    id: '/angsuran',
    path: '/angsuran',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAnggotaRoute =
  AuthenticatedAdminAnggotaRouteImport.update({
    id: '/anggota',
    path: '/anggota',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAnalitikRoute =
  AuthenticatedAdminAnalitikRouteImport.update({
    id: '/analitik',
    path: '/analitik',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAktivitasRoute =
  AuthenticatedAdminAktivitasRouteImport.update({
    id: '/aktivitas',
    path: '/aktivitas',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAkadRoute = AuthenticatedAdminAkadRouteImport.update({
  id: '/akad',
  path: '/akad',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const ApiPublicHooksDailyRemindersRoute =
  ApiPublicHooksDailyRemindersRouteImport.update({
    id: '/api/public/hooks/daily-reminders',
    path: '/api/public/hooks/daily-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAutoReleaseEscrowRoute =
  ApiPublicHooksAutoReleaseEscrowRouteImport.update({
    id: '/api/public/hooks/auto-release-escrow',
    path: '/api/public/hooks/auto-release-escrow',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAutoDebetWajibRoute =
  ApiPublicHooksAutoDebetWajibRouteImport.update({
    id: '/api/public/hooks/auto-debet-wajib',
    path: '/api/public/hooks/auto-debet-wajib',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAccrueFeesRoute =
  ApiPublicHooksAccrueFeesRouteImport.update({
    id: '/api/public/hooks/accrue-fees',
    path: '/api/public/hooks/accrue-fees',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedSekolahPengadaanIdRoute =
  AuthenticatedSekolahPengadaanIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedSekolahPengadaanRoute,
  } as any)
const AuthenticatedGerejaPengadaanIdRoute =
  AuthenticatedGerejaPengadaanIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedGerejaPengadaanRoute,
  } as any)
const AuthenticatedAdminSekolahPengadaanRoute =
  AuthenticatedAdminSekolahPengadaanRouteImport.update({
    id: '/sekolah/pengadaan',
    path: '/sekolah/pengadaan',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminGerejaPengadaanRoute =
  AuthenticatedAdminGerejaPengadaanRouteImport.update({
    id: '/gereja/pengadaan',
    path: '/gereja/pengadaan',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/berita': typeof BeritaRouteWithChildren
  '/daftar-anggota': typeof DaftarAnggotaRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/tentang': typeof TentangRoute
  '/verify/': typeof VerifyRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/angsuran': typeof AuthenticatedAngsuranRoute
  '/approval': typeof AuthenticatedApprovalRoute
  '/bantuan': typeof AuthenticatedBantuanRoute
  '/buku-besar': typeof AuthenticatedBukuBesarRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dashboard-belanja': typeof AuthenticatedDashboardBelanjaRoute
  '/dokumen': typeof AuthenticatedDokumenRoute
  '/favorit': typeof AuthenticatedFavoritRoute
  '/kalkulator': typeof AuthenticatedKalkulatorRoute
  '/lowongan': typeof AuthenticatedLowonganRoute
  '/marketplace-saya': typeof AuthenticatedMarketplaceSayaRoute
  '/penjamin': typeof AuthenticatedPenjaminRoute
  '/pinjaman': typeof AuthenticatedPinjamanRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/rapat': typeof AuthenticatedRapatRoute
  '/riwayat': typeof AuthenticatedRiwayatRoute
  '/saldo': typeof AuthenticatedSaldoRoute
  '/shu': typeof AuthenticatedShuRoute
  '/simpanan': typeof AuthenticatedSimpananRoute
  '/survei': typeof AuthenticatedSurveiRoute
  '/tabungan-berjangka': typeof AuthenticatedTabunganBerjangkaRoute
  '/transaksi-saya': typeof AuthenticatedTransaksiSayaRoute
  '/voting': typeof AuthenticatedVotingRoute
  '/berita/$slug': typeof BeritaSlugRoute
  '/marketplace/checkout': typeof MarketplaceCheckoutRoute
  '/marketplace/keranjang': typeof MarketplaceKeranjangRoute
  '/berita/': typeof BeritaIndexRoute
  '/marketplace/': typeof MarketplaceIndexRoute
  '/admin/akad': typeof AuthenticatedAdminAkadRoute
  '/admin/aktivitas': typeof AuthenticatedAdminAktivitasRoute
  '/admin/analitik': typeof AuthenticatedAdminAnalitikRoute
  '/admin/anggota': typeof AuthenticatedAdminAnggotaRoute
  '/admin/angsuran': typeof AuthenticatedAdminAngsuranRoute
  '/admin/approval': typeof AuthenticatedAdminApprovalRoute
  '/admin/arsip-transaksi': typeof AuthenticatedAdminArsipTransaksiRoute
  '/admin/aset': typeof AuthenticatedAdminAsetRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/backup': typeof AuthenticatedAdminBackupRoute
  '/admin/berita': typeof AuthenticatedAdminBeritaRoute
  '/admin/buku-besar': typeof AuthenticatedAdminBukuBesarRoute
  '/admin/buku-kas': typeof AuthenticatedAdminBukuKasRoute
  '/admin/dana-cadangan': typeof AuthenticatedAdminDanaCadanganRoute
  '/admin/escrow': typeof AuthenticatedAdminEscrowRoute
  '/admin/fee': typeof AuthenticatedAdminFeeRoute
  '/admin/komplain': typeof AuthenticatedAdminKomplainRoute
  '/admin/kupon': typeof AuthenticatedAdminKuponRoute
  '/admin/laporan': typeof AuthenticatedAdminLaporanRoute
  '/admin/laporan-rat': typeof AuthenticatedAdminLaporanRatRoute
  '/admin/laporan-sak': typeof AuthenticatedAdminLaporanSakRoute
  '/admin/lowongan': typeof AuthenticatedAdminLowonganRoute
  '/admin/marketplace': typeof AuthenticatedAdminMarketplaceRoute
  '/admin/notifikasi-wa': typeof AuthenticatedAdminNotifikasiWaRoute
  '/admin/opex': typeof AuthenticatedAdminOpexRoute
  '/admin/penagihan': typeof AuthenticatedAdminPenagihanRoute
  '/admin/pengaturan': typeof AuthenticatedAdminPengaturanRoute
  '/admin/penjamin': typeof AuthenticatedAdminPenjaminRoute
  '/admin/pinjaman': typeof AuthenticatedAdminPinjamanRoute
  '/admin/qris': typeof AuthenticatedAdminQrisRoute
  '/admin/rapb': typeof AuthenticatedAdminRapbRoute
  '/admin/rekonsiliasi': typeof AuthenticatedAdminRekonsiliasiRoute
  '/admin/role': typeof AuthenticatedAdminRoleRoute
  '/admin/seller-verify': typeof AuthenticatedAdminSellerVerifyRoute
  '/admin/shu': typeof AuthenticatedAdminShuRoute
  '/admin/simpanan': typeof AuthenticatedAdminSimpananRoute
  '/admin/statistik': typeof AuthenticatedAdminStatistikRoute
  '/admin/support': typeof AuthenticatedAdminSupportRoute
  '/admin/surat': typeof AuthenticatedAdminSuratRoute
  '/admin/survei': typeof AuthenticatedAdminSurveiRoute
  '/admin/tabungan-berjangka': typeof AuthenticatedAdminTabunganBerjangkaRoute
  '/admin/verifikasi-pinjaman': typeof AuthenticatedAdminVerifikasiPinjamanRoute
  '/admin/voting': typeof AuthenticatedAdminVotingRoute
  '/gereja/pengadaan': typeof AuthenticatedGerejaPengadaanRouteWithChildren
  '/sekolah/pengadaan': typeof AuthenticatedSekolahPengadaanRouteWithChildren
  '/marketplace/produk/$id': typeof MarketplaceProdukIdRoute
  '/marketplace/toko/$slug': typeof MarketplaceTokoSlugRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/gereja/pengadaan': typeof AuthenticatedAdminGerejaPengadaanRoute
  '/admin/sekolah/pengadaan': typeof AuthenticatedAdminSekolahPengadaanRoute
  '/gereja/pengadaan/$id': typeof AuthenticatedGerejaPengadaanIdRoute
  '/sekolah/pengadaan/$id': typeof AuthenticatedSekolahPengadaanIdRoute
  '/api/public/hooks/accrue-fees': typeof ApiPublicHooksAccrueFeesRoute
  '/api/public/hooks/auto-debet-wajib': typeof ApiPublicHooksAutoDebetWajibRoute
  '/api/public/hooks/auto-release-escrow': typeof ApiPublicHooksAutoReleaseEscrowRoute
  '/api/public/hooks/daily-reminders': typeof ApiPublicHooksDailyRemindersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/daftar-anggota': typeof DaftarAnggotaRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/tentang': typeof TentangRoute
  '/verify': typeof VerifyRoute
  '/angsuran': typeof AuthenticatedAngsuranRoute
  '/approval': typeof AuthenticatedApprovalRoute
  '/bantuan': typeof AuthenticatedBantuanRoute
  '/buku-besar': typeof AuthenticatedBukuBesarRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dashboard-belanja': typeof AuthenticatedDashboardBelanjaRoute
  '/dokumen': typeof AuthenticatedDokumenRoute
  '/favorit': typeof AuthenticatedFavoritRoute
  '/kalkulator': typeof AuthenticatedKalkulatorRoute
  '/lowongan': typeof AuthenticatedLowonganRoute
  '/marketplace-saya': typeof AuthenticatedMarketplaceSayaRoute
  '/penjamin': typeof AuthenticatedPenjaminRoute
  '/pinjaman': typeof AuthenticatedPinjamanRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/rapat': typeof AuthenticatedRapatRoute
  '/riwayat': typeof AuthenticatedRiwayatRoute
  '/saldo': typeof AuthenticatedSaldoRoute
  '/shu': typeof AuthenticatedShuRoute
  '/simpanan': typeof AuthenticatedSimpananRoute
  '/survei': typeof AuthenticatedSurveiRoute
  '/tabungan-berjangka': typeof AuthenticatedTabunganBerjangkaRoute
  '/transaksi-saya': typeof AuthenticatedTransaksiSayaRoute
  '/voting': typeof AuthenticatedVotingRoute
  '/berita/$slug': typeof BeritaSlugRoute
  '/marketplace/checkout': typeof MarketplaceCheckoutRoute
  '/marketplace/keranjang': typeof MarketplaceKeranjangRoute
  '/berita': typeof BeritaIndexRoute
  '/marketplace': typeof MarketplaceIndexRoute
  '/admin/akad': typeof AuthenticatedAdminAkadRoute
  '/admin/aktivitas': typeof AuthenticatedAdminAktivitasRoute
  '/admin/analitik': typeof AuthenticatedAdminAnalitikRoute
  '/admin/anggota': typeof AuthenticatedAdminAnggotaRoute
  '/admin/angsuran': typeof AuthenticatedAdminAngsuranRoute
  '/admin/approval': typeof AuthenticatedAdminApprovalRoute
  '/admin/arsip-transaksi': typeof AuthenticatedAdminArsipTransaksiRoute
  '/admin/aset': typeof AuthenticatedAdminAsetRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/backup': typeof AuthenticatedAdminBackupRoute
  '/admin/berita': typeof AuthenticatedAdminBeritaRoute
  '/admin/buku-besar': typeof AuthenticatedAdminBukuBesarRoute
  '/admin/buku-kas': typeof AuthenticatedAdminBukuKasRoute
  '/admin/dana-cadangan': typeof AuthenticatedAdminDanaCadanganRoute
  '/admin/escrow': typeof AuthenticatedAdminEscrowRoute
  '/admin/fee': typeof AuthenticatedAdminFeeRoute
  '/admin/komplain': typeof AuthenticatedAdminKomplainRoute
  '/admin/kupon': typeof AuthenticatedAdminKuponRoute
  '/admin/laporan': typeof AuthenticatedAdminLaporanRoute
  '/admin/laporan-rat': typeof AuthenticatedAdminLaporanRatRoute
  '/admin/laporan-sak': typeof AuthenticatedAdminLaporanSakRoute
  '/admin/lowongan': typeof AuthenticatedAdminLowonganRoute
  '/admin/marketplace': typeof AuthenticatedAdminMarketplaceRoute
  '/admin/notifikasi-wa': typeof AuthenticatedAdminNotifikasiWaRoute
  '/admin/opex': typeof AuthenticatedAdminOpexRoute
  '/admin/penagihan': typeof AuthenticatedAdminPenagihanRoute
  '/admin/pengaturan': typeof AuthenticatedAdminPengaturanRoute
  '/admin/penjamin': typeof AuthenticatedAdminPenjaminRoute
  '/admin/pinjaman': typeof AuthenticatedAdminPinjamanRoute
  '/admin/qris': typeof AuthenticatedAdminQrisRoute
  '/admin/rapb': typeof AuthenticatedAdminRapbRoute
  '/admin/rekonsiliasi': typeof AuthenticatedAdminRekonsiliasiRoute
  '/admin/role': typeof AuthenticatedAdminRoleRoute
  '/admin/seller-verify': typeof AuthenticatedAdminSellerVerifyRoute
  '/admin/shu': typeof AuthenticatedAdminShuRoute
  '/admin/simpanan': typeof AuthenticatedAdminSimpananRoute
  '/admin/statistik': typeof AuthenticatedAdminStatistikRoute
  '/admin/support': typeof AuthenticatedAdminSupportRoute
  '/admin/surat': typeof AuthenticatedAdminSuratRoute
  '/admin/survei': typeof AuthenticatedAdminSurveiRoute
  '/admin/tabungan-berjangka': typeof AuthenticatedAdminTabunganBerjangkaRoute
  '/admin/verifikasi-pinjaman': typeof AuthenticatedAdminVerifikasiPinjamanRoute
  '/admin/voting': typeof AuthenticatedAdminVotingRoute
  '/gereja/pengadaan': typeof AuthenticatedGerejaPengadaanRouteWithChildren
  '/sekolah/pengadaan': typeof AuthenticatedSekolahPengadaanRouteWithChildren
  '/marketplace/produk/$id': typeof MarketplaceProdukIdRoute
  '/marketplace/toko/$slug': typeof MarketplaceTokoSlugRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/gereja/pengadaan': typeof AuthenticatedAdminGerejaPengadaanRoute
  '/admin/sekolah/pengadaan': typeof AuthenticatedAdminSekolahPengadaanRoute
  '/gereja/pengadaan/$id': typeof AuthenticatedGerejaPengadaanIdRoute
  '/sekolah/pengadaan/$id': typeof AuthenticatedSekolahPengadaanIdRoute
  '/api/public/hooks/accrue-fees': typeof ApiPublicHooksAccrueFeesRoute
  '/api/public/hooks/auto-debet-wajib': typeof ApiPublicHooksAutoDebetWajibRoute
  '/api/public/hooks/auto-release-escrow': typeof ApiPublicHooksAutoReleaseEscrowRoute
  '/api/public/hooks/daily-reminders': typeof ApiPublicHooksDailyRemindersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/berita': typeof BeritaRouteWithChildren
  '/daftar-anggota': typeof DaftarAnggotaRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/tentang': typeof TentangRoute
  '/verify/': typeof VerifyRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/angsuran': typeof AuthenticatedAngsuranRoute
  '/_authenticated/approval': typeof AuthenticatedApprovalRoute
  '/_authenticated/bantuan': typeof AuthenticatedBantuanRoute
  '/_authenticated/buku-besar': typeof AuthenticatedBukuBesarRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/dashboard-belanja': typeof AuthenticatedDashboardBelanjaRoute
  '/_authenticated/dokumen': typeof AuthenticatedDokumenRoute
  '/_authenticated/favorit': typeof AuthenticatedFavoritRoute
  '/_authenticated/kalkulator': typeof AuthenticatedKalkulatorRoute
  '/_authenticated/lowongan': typeof AuthenticatedLowonganRoute
  '/_authenticated/marketplace-saya': typeof AuthenticatedMarketplaceSayaRoute
  '/_authenticated/penjamin': typeof AuthenticatedPenjaminRoute
  '/_authenticated/pinjaman': typeof AuthenticatedPinjamanRoute
  '/_authenticated/profil': typeof AuthenticatedProfilRoute
  '/_authenticated/rapat': typeof AuthenticatedRapatRoute
  '/_authenticated/riwayat': typeof AuthenticatedRiwayatRoute
  '/_authenticated/saldo': typeof AuthenticatedSaldoRoute
  '/_authenticated/shu': typeof AuthenticatedShuRoute
  '/_authenticated/simpanan': typeof AuthenticatedSimpananRoute
  '/_authenticated/survei': typeof AuthenticatedSurveiRoute
  '/_authenticated/tabungan-berjangka': typeof AuthenticatedTabunganBerjangkaRoute
  '/_authenticated/transaksi-saya': typeof AuthenticatedTransaksiSayaRoute
  '/_authenticated/voting': typeof AuthenticatedVotingRoute
  '/berita/$slug': typeof BeritaSlugRoute
  '/marketplace/checkout': typeof MarketplaceCheckoutRoute
  '/marketplace/keranjang': typeof MarketplaceKeranjangRoute
  '/berita/': typeof BeritaIndexRoute
  '/marketplace/': typeof MarketplaceIndexRoute
  '/_authenticated/admin/akad': typeof AuthenticatedAdminAkadRoute
  '/_authenticated/admin/aktivitas': typeof AuthenticatedAdminAktivitasRoute
  '/_authenticated/admin/analitik': typeof AuthenticatedAdminAnalitikRoute
  '/_authenticated/admin/anggota': typeof AuthenticatedAdminAnggotaRoute
  '/_authenticated/admin/angsuran': typeof AuthenticatedAdminAngsuranRoute
  '/_authenticated/admin/approval': typeof AuthenticatedAdminApprovalRoute
  '/_authenticated/admin/arsip-transaksi': typeof AuthenticatedAdminArsipTransaksiRoute
  '/_authenticated/admin/aset': typeof AuthenticatedAdminAsetRoute
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/backup': typeof AuthenticatedAdminBackupRoute
  '/_authenticated/admin/berita': typeof AuthenticatedAdminBeritaRoute
  '/_authenticated/admin/buku-besar': typeof AuthenticatedAdminBukuBesarRoute
  '/_authenticated/admin/buku-kas': typeof AuthenticatedAdminBukuKasRoute
  '/_authenticated/admin/dana-cadangan': typeof AuthenticatedAdminDanaCadanganRoute
  '/_authenticated/admin/escrow': typeof AuthenticatedAdminEscrowRoute
  '/_authenticated/admin/fee': typeof AuthenticatedAdminFeeRoute
  '/_authenticated/admin/komplain': typeof AuthenticatedAdminKomplainRoute
  '/_authenticated/admin/kupon': typeof AuthenticatedAdminKuponRoute
  '/_authenticated/admin/laporan': typeof AuthenticatedAdminLaporanRoute
  '/_authenticated/admin/laporan-rat': typeof AuthenticatedAdminLaporanRatRoute
  '/_authenticated/admin/laporan-sak': typeof AuthenticatedAdminLaporanSakRoute
  '/_authenticated/admin/lowongan': typeof AuthenticatedAdminLowonganRoute
  '/_authenticated/admin/marketplace': typeof AuthenticatedAdminMarketplaceRoute
  '/_authenticated/admin/notifikasi-wa': typeof AuthenticatedAdminNotifikasiWaRoute
  '/_authenticated/admin/opex': typeof AuthenticatedAdminOpexRoute
  '/_authenticated/admin/penagihan': typeof AuthenticatedAdminPenagihanRoute
  '/_authenticated/admin/pengaturan': typeof AuthenticatedAdminPengaturanRoute
  '/_authenticated/admin/penjamin': typeof AuthenticatedAdminPenjaminRoute
  '/_authenticated/admin/pinjaman': typeof AuthenticatedAdminPinjamanRoute
  '/_authenticated/admin/qris': typeof AuthenticatedAdminQrisRoute
  '/_authenticated/admin/rapb': typeof AuthenticatedAdminRapbRoute
  '/_authenticated/admin/rekonsiliasi': typeof AuthenticatedAdminRekonsiliasiRoute
  '/_authenticated/admin/role': typeof AuthenticatedAdminRoleRoute
  '/_authenticated/admin/seller-verify': typeof AuthenticatedAdminSellerVerifyRoute
  '/_authenticated/admin/shu': typeof AuthenticatedAdminShuRoute
  '/_authenticated/admin/simpanan': typeof AuthenticatedAdminSimpananRoute
  '/_authenticated/admin/statistik': typeof AuthenticatedAdminStatistikRoute
  '/_authenticated/admin/support': typeof AuthenticatedAdminSupportRoute
  '/_authenticated/admin/surat': typeof AuthenticatedAdminSuratRoute
  '/_authenticated/admin/survei': typeof AuthenticatedAdminSurveiRoute
  '/_authenticated/admin/tabungan-berjangka': typeof AuthenticatedAdminTabunganBerjangkaRoute
  '/_authenticated/admin/verifikasi-pinjaman': typeof AuthenticatedAdminVerifikasiPinjamanRoute
  '/_authenticated/admin/voting': typeof AuthenticatedAdminVotingRoute
  '/_authenticated/gereja/pengadaan': typeof AuthenticatedGerejaPengadaanRouteWithChildren
  '/_authenticated/sekolah/pengadaan': typeof AuthenticatedSekolahPengadaanRouteWithChildren
  '/marketplace/produk/$id': typeof MarketplaceProdukIdRoute
  '/marketplace/toko/$slug': typeof MarketplaceTokoSlugRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/gereja/pengadaan': typeof AuthenticatedAdminGerejaPengadaanRoute
  '/_authenticated/admin/sekolah/pengadaan': typeof AuthenticatedAdminSekolahPengadaanRoute
  '/_authenticated/gereja/pengadaan/$id': typeof AuthenticatedGerejaPengadaanIdRoute
  '/_authenticated/sekolah/pengadaan/$id': typeof AuthenticatedSekolahPengadaanIdRoute
  '/api/public/hooks/accrue-fees': typeof ApiPublicHooksAccrueFeesRoute
  '/api/public/hooks/auto-debet-wajib': typeof ApiPublicHooksAutoDebetWajibRoute
  '/api/public/hooks/auto-release-escrow': typeof ApiPublicHooksAutoReleaseEscrowRoute
  '/api/public/hooks/daily-reminders': typeof ApiPublicHooksDailyRemindersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/berita'
    | '/daftar-anggota'
    | '/forgot-password'
    | '/reset-password'
    | '/tentang'
    | '/verify/'
    | '/admin'
    | '/angsuran'
    | '/approval'
    | '/bantuan'
    | '/buku-besar'
    | '/dashboard'
    | '/dashboard-belanja'
    | '/dokumen'
    | '/favorit'
    | '/kalkulator'
    | '/lowongan'
    | '/marketplace-saya'
    | '/penjamin'
    | '/pinjaman'
    | '/profil'
    | '/rapat'
    | '/riwayat'
    | '/saldo'
    | '/shu'
    | '/simpanan'
    | '/survei'
    | '/tabungan-berjangka'
    | '/transaksi-saya'
    | '/voting'
    | '/berita/$slug'
    | '/marketplace/checkout'
    | '/marketplace/keranjang'
    | '/berita/'
    | '/marketplace/'
    | '/admin/akad'
    | '/admin/aktivitas'
    | '/admin/analitik'
    | '/admin/anggota'
    | '/admin/angsuran'
    | '/admin/approval'
    | '/admin/arsip-transaksi'
    | '/admin/aset'
    | '/admin/audit'
    | '/admin/backup'
    | '/admin/berita'
    | '/admin/buku-besar'
    | '/admin/buku-kas'
    | '/admin/dana-cadangan'
    | '/admin/escrow'
    | '/admin/fee'
    | '/admin/komplain'
    | '/admin/kupon'
    | '/admin/laporan'
    | '/admin/laporan-rat'
    | '/admin/laporan-sak'
    | '/admin/lowongan'
    | '/admin/marketplace'
    | '/admin/notifikasi-wa'
    | '/admin/opex'
    | '/admin/penagihan'
    | '/admin/pengaturan'
    | '/admin/penjamin'
    | '/admin/pinjaman'
    | '/admin/qris'
    | '/admin/rapb'
    | '/admin/rekonsiliasi'
    | '/admin/role'
    | '/admin/seller-verify'
    | '/admin/shu'
    | '/admin/simpanan'
    | '/admin/statistik'
    | '/admin/support'
    | '/admin/surat'
    | '/admin/survei'
    | '/admin/tabungan-berjangka'
    | '/admin/verifikasi-pinjaman'
    | '/admin/voting'
    | '/gereja/pengadaan'
    | '/sekolah/pengadaan'
    | '/marketplace/produk/$id'
    | '/marketplace/toko/$slug'
    | '/admin/'
    | '/admin/gereja/pengadaan'
    | '/admin/sekolah/pengadaan'
    | '/gereja/pengadaan/$id'
    | '/sekolah/pengadaan/$id'
    | '/api/public/hooks/accrue-fees'
    | '/api/public/hooks/auto-debet-wajib'
    | '/api/public/hooks/auto-release-escrow'
    | '/api/public/hooks/daily-reminders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/daftar-anggota'
    | '/forgot-password'
    | '/reset-password'
    | '/tentang'
    | '/verify'
    | '/angsuran'
    | '/approval'
    | '/bantuan'
    | '/buku-besar'
    | '/dashboard'
    | '/dashboard-belanja'
    | '/dokumen'
    | '/favorit'
    | '/kalkulator'
    | '/lowongan'
    | '/marketplace-saya'
    | '/penjamin'
    | '/pinjaman'
    | '/profil'
    | '/rapat'
    | '/riwayat'
    | '/saldo'
    | '/shu'
    | '/simpanan'
    | '/survei'
    | '/tabungan-berjangka'
    | '/transaksi-saya'
    | '/voting'
    | '/berita/$slug'
    | '/marketplace/checkout'
    | '/marketplace/keranjang'
    | '/berita'
    | '/marketplace'
    | '/admin/akad'
    | '/admin/aktivitas'
    | '/admin/analitik'
    | '/admin/anggota'
    | '/admin/angsuran'
    | '/admin/approval'
    | '/admin/arsip-transaksi'
    | '/admin/aset'
    | '/admin/audit'
    | '/admin/backup'
    | '/admin/berita'
    | '/admin/buku-besar'
    | '/admin/buku-kas'
    | '/admin/dana-cadangan'
    | '/admin/escrow'
    | '/admin/fee'
    | '/admin/komplain'
    | '/admin/kupon'
    | '/admin/laporan'
    | '/admin/laporan-rat'
    | '/admin/laporan-sak'
    | '/admin/lowongan'
    | '/admin/marketplace'
    | '/admin/notifikasi-wa'
    | '/admin/opex'
    | '/admin/penagihan'
    | '/admin/pengaturan'
    | '/admin/penjamin'
    | '/admin/pinjaman'
    | '/admin/qris'
    | '/admin/rapb'
    | '/admin/rekonsiliasi'
    | '/admin/role'
    | '/admin/seller-verify'
    | '/admin/shu'
    | '/admin/simpanan'
    | '/admin/statistik'
    | '/admin/support'
    | '/admin/surat'
    | '/admin/survei'
    | '/admin/tabungan-berjangka'
    | '/admin/verifikasi-pinjaman'
    | '/admin/voting'
    | '/gereja/pengadaan'
    | '/sekolah/pengadaan'
    | '/marketplace/produk/$id'
    | '/marketplace/toko/$slug'
    | '/admin'
    | '/admin/gereja/pengadaan'
    | '/admin/sekolah/pengadaan'
    | '/gereja/pengadaan/$id'
    | '/sekolah/pengadaan/$id'
    | '/api/public/hooks/accrue-fees'
    | '/api/public/hooks/auto-debet-wajib'
    | '/api/public/hooks/auto-release-escrow'
    | '/api/public/hooks/daily-reminders'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/berita'
    | '/daftar-anggota'
    | '/forgot-password'
    | '/reset-password'
    | '/tentang'
    | '/verify/'
    | '/_authenticated/admin'
    | '/_authenticated/angsuran'
    | '/_authenticated/approval'
    | '/_authenticated/bantuan'
    | '/_authenticated/buku-besar'
    | '/_authenticated/dashboard'
    | '/_authenticated/dashboard-belanja'
    | '/_authenticated/dokumen'
    | '/_authenticated/favorit'
    | '/_authenticated/kalkulator'
    | '/_authenticated/lowongan'
    | '/_authenticated/marketplace-saya'
    | '/_authenticated/penjamin'
    | '/_authenticated/pinjaman'
    | '/_authenticated/profil'
    | '/_authenticated/rapat'
    | '/_authenticated/riwayat'
    | '/_authenticated/saldo'
    | '/_authenticated/shu'
    | '/_authenticated/simpanan'
    | '/_authenticated/survei'
    | '/_authenticated/tabungan-berjangka'
    | '/_authenticated/transaksi-saya'
    | '/_authenticated/voting'
    | '/berita/$slug'
    | '/marketplace/checkout'
    | '/marketplace/keranjang'
    | '/berita/'
    | '/marketplace/'
    | '/_authenticated/admin/akad'
    | '/_authenticated/admin/aktivitas'
    | '/_authenticated/admin/analitik'
    | '/_authenticated/admin/anggota'
    | '/_authenticated/admin/angsuran'
    | '/_authenticated/admin/approval'
    | '/_authenticated/admin/arsip-transaksi'
    | '/_authenticated/admin/aset'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/backup'
    | '/_authenticated/admin/berita'
    | '/_authenticated/admin/buku-besar'
    | '/_authenticated/admin/buku-kas'
    | '/_authenticated/admin/dana-cadangan'
    | '/_authenticated/admin/escrow'
    | '/_authenticated/admin/fee'
    | '/_authenticated/admin/komplain'
    | '/_authenticated/admin/kupon'
    | '/_authenticated/admin/laporan'
    | '/_authenticated/admin/laporan-rat'
    | '/_authenticated/admin/laporan-sak'
    | '/_authenticated/admin/lowongan'
    | '/_authenticated/admin/marketplace'
    | '/_authenticated/admin/notifikasi-wa'
    | '/_authenticated/admin/opex'
    | '/_authenticated/admin/penagihan'
    | '/_authenticated/admin/pengaturan'
    | '/_authenticated/admin/penjamin'
    | '/_authenticated/admin/pinjaman'
    | '/_authenticated/admin/qris'
    | '/_authenticated/admin/rapb'
    | '/_authenticated/admin/rekonsiliasi'
    | '/_authenticated/admin/role'
    | '/_authenticated/admin/seller-verify'
    | '/_authenticated/admin/shu'
    | '/_authenticated/admin/simpanan'
    | '/_authenticated/admin/statistik'
    | '/_authenticated/admin/support'
    | '/_authenticated/admin/surat'
    | '/_authenticated/admin/survei'
    | '/_authenticated/admin/tabungan-berjangka'
    | '/_authenticated/admin/verifikasi-pinjaman'
    | '/_authenticated/admin/voting'
    | '/_authenticated/gereja/pengadaan'
    | '/_authenticated/sekolah/pengadaan'
    | '/marketplace/produk/$id'
    | '/marketplace/toko/$slug'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/gereja/pengadaan'
    | '/_authenticated/admin/sekolah/pengadaan'
    | '/_authenticated/gereja/pengadaan/$id'
    | '/_authenticated/sekolah/pengadaan/$id'
    | '/api/public/hooks/accrue-fees'
    | '/api/public/hooks/auto-debet-wajib'
    | '/api/public/hooks/auto-release-escrow'
    | '/api/public/hooks/daily-reminders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  BeritaRoute: typeof BeritaRouteWithChildren
  DaftarAnggotaRoute: typeof DaftarAnggotaRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TentangRoute: typeof TentangRoute
  VerifyRoute: typeof VerifyRoute
  MarketplaceCheckoutRoute: typeof MarketplaceCheckoutRoute
  MarketplaceKeranjangRoute: typeof MarketplaceKeranjangRoute
  MarketplaceIndexRoute: typeof MarketplaceIndexRoute
  MarketplaceProdukIdRoute: typeof MarketplaceProdukIdRoute
  MarketplaceTokoSlugRoute: typeof MarketplaceTokoSlugRoute
  ApiPublicHooksAccrueFeesRoute: typeof ApiPublicHooksAccrueFeesRoute
  ApiPublicHooksAutoDebetWajibRoute: typeof ApiPublicHooksAutoDebetWajibRoute
  ApiPublicHooksAutoReleaseEscrowRoute: typeof ApiPublicHooksAutoReleaseEscrowRoute
  ApiPublicHooksDailyRemindersRoute: typeof ApiPublicHooksDailyRemindersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tentang': {
      id: '/tentang'
      path: '/tentang'
      fullPath: '/tentang'
      preLoaderRoute: typeof TentangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daftar-anggota': {
      id: '/daftar-anggota'
      path: '/daftar-anggota'
      fullPath: '/daftar-anggota'
      preLoaderRoute: typeof DaftarAnggotaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/berita': {
      id: '/berita'
      path: '/berita'
      fullPath: '/berita'
      preLoaderRoute: typeof BeritaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/': {
      id: '/marketplace/'
      path: '/marketplace'
      fullPath: '/marketplace/'
      preLoaderRoute: typeof MarketplaceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/berita/': {
      id: '/berita/'
      path: '/'
      fullPath: '/berita/'
      preLoaderRoute: typeof BeritaIndexRouteImport
      parentRoute: typeof BeritaRoute
    }
    '/marketplace/keranjang': {
      id: '/marketplace/keranjang'
      path: '/marketplace/keranjang'
      fullPath: '/marketplace/keranjang'
      preLoaderRoute: typeof MarketplaceKeranjangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/checkout': {
      id: '/marketplace/checkout'
      path: '/marketplace/checkout'
      fullPath: '/marketplace/checkout'
      preLoaderRoute: typeof MarketplaceCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/berita/$slug': {
      id: '/berita/$slug'
      path: '/$slug'
      fullPath: '/berita/$slug'
      preLoaderRoute: typeof BeritaSlugRouteImport
      parentRoute: typeof BeritaRoute
    }
    '/_authenticated/voting': {
      id: '/_authenticated/voting'
      path: '/voting'
      fullPath: '/voting'
      preLoaderRoute: typeof AuthenticatedVotingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/transaksi-saya': {
      id: '/_authenticated/transaksi-saya'
      path: '/transaksi-saya'
      fullPath: '/transaksi-saya'
      preLoaderRoute: typeof AuthenticatedTransaksiSayaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tabungan-berjangka': {
      id: '/_authenticated/tabungan-berjangka'
      path: '/tabungan-berjangka'
      fullPath: '/tabungan-berjangka'
      preLoaderRoute: typeof AuthenticatedTabunganBerjangkaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/survei': {
      id: '/_authenticated/survei'
      path: '/survei'
      fullPath: '/survei'
      preLoaderRoute: typeof AuthenticatedSurveiRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/simpanan': {
      id: '/_authenticated/simpanan'
      path: '/simpanan'
      fullPath: '/simpanan'
      preLoaderRoute: typeof AuthenticatedSimpananRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/shu': {
      id: '/_authenticated/shu'
      path: '/shu'
      fullPath: '/shu'
      preLoaderRoute: typeof AuthenticatedShuRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/saldo': {
      id: '/_authenticated/saldo'
      path: '/saldo'
      fullPath: '/saldo'
      preLoaderRoute: typeof AuthenticatedSaldoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/riwayat': {
      id: '/_authenticated/riwayat'
      path: '/riwayat'
      fullPath: '/riwayat'
      preLoaderRoute: typeof AuthenticatedRiwayatRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rapat': {
      id: '/_authenticated/rapat'
      path: '/rapat'
      fullPath: '/rapat'
      preLoaderRoute: typeof AuthenticatedRapatRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profil': {
      id: '/_authenticated/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof AuthenticatedProfilRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pinjaman': {
      id: '/_authenticated/pinjaman'
      path: '/pinjaman'
      fullPath: '/pinjaman'
      preLoaderRoute: typeof AuthenticatedPinjamanRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/penjamin': {
      id: '/_authenticated/penjamin'
      path: '/penjamin'
      fullPath: '/penjamin'
      preLoaderRoute: typeof AuthenticatedPenjaminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/marketplace-saya': {
      id: '/_authenticated/marketplace-saya'
      path: '/marketplace-saya'
      fullPath: '/marketplace-saya'
      preLoaderRoute: typeof AuthenticatedMarketplaceSayaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lowongan': {
      id: '/_authenticated/lowongan'
      path: '/lowongan'
      fullPath: '/lowongan'
      preLoaderRoute: typeof AuthenticatedLowonganRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/kalkulator': {
      id: '/_authenticated/kalkulator'
      path: '/kalkulator'
      fullPath: '/kalkulator'
      preLoaderRoute: typeof AuthenticatedKalkulatorRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/favorit': {
      id: '/_authenticated/favorit'
      path: '/favorit'
      fullPath: '/favorit'
      preLoaderRoute: typeof AuthenticatedFavoritRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dokumen': {
      id: '/_authenticated/dokumen'
      path: '/dokumen'
      fullPath: '/dokumen'
      preLoaderRoute: typeof AuthenticatedDokumenRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard-belanja': {
      id: '/_authenticated/dashboard-belanja'
      path: '/dashboard-belanja'
      fullPath: '/dashboard-belanja'
      preLoaderRoute: typeof AuthenticatedDashboardBelanjaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/buku-besar': {
      id: '/_authenticated/buku-besar'
      path: '/buku-besar'
      fullPath: '/buku-besar'
      preLoaderRoute: typeof AuthenticatedBukuBesarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bantuan': {
      id: '/_authenticated/bantuan'
      path: '/bantuan'
      fullPath: '/bantuan'
      preLoaderRoute: typeof AuthenticatedBantuanRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/approval': {
      id: '/_authenticated/approval'
      path: '/approval'
      fullPath: '/approval'
      preLoaderRoute: typeof AuthenticatedApprovalRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/angsuran': {
      id: '/_authenticated/angsuran'
      path: '/angsuran'
      fullPath: '/angsuran'
      preLoaderRoute: typeof AuthenticatedAngsuranRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/verify/': {
      id: '/verify/'
      path: '/verify'
      fullPath: '/verify/'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/marketplace/toko/$slug': {
      id: '/marketplace/toko/$slug'
      path: '/marketplace/toko/$slug'
      fullPath: '/marketplace/toko/$slug'
      preLoaderRoute: typeof MarketplaceTokoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/produk/$id': {
      id: '/marketplace/produk/$id'
      path: '/marketplace/produk/$id'
      fullPath: '/marketplace/produk/$id'
      preLoaderRoute: typeof MarketplaceProdukIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/sekolah/pengadaan': {
      id: '/_authenticated/sekolah/pengadaan'
      path: '/sekolah/pengadaan'
      fullPath: '/sekolah/pengadaan'
      preLoaderRoute: typeof AuthenticatedSekolahPengadaanRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/gereja/pengadaan': {
      id: '/_authenticated/gereja/pengadaan'
      path: '/gereja/pengadaan'
      fullPath: '/gereja/pengadaan'
      preLoaderRoute: typeof AuthenticatedGerejaPengadaanRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/voting': {
      id: '/_authenticated/admin/voting'
      path: '/voting'
      fullPath: '/admin/voting'
      preLoaderRoute: typeof AuthenticatedAdminVotingRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/verifikasi-pinjaman': {
      id: '/_authenticated/admin/verifikasi-pinjaman'
      path: '/verifikasi-pinjaman'
      fullPath: '/admin/verifikasi-pinjaman'
      preLoaderRoute: typeof AuthenticatedAdminVerifikasiPinjamanRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/tabungan-berjangka': {
      id: '/_authenticated/admin/tabungan-berjangka'
      path: '/tabungan-berjangka'
      fullPath: '/admin/tabungan-berjangka'
      preLoaderRoute: typeof AuthenticatedAdminTabunganBerjangkaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/survei': {
      id: '/_authenticated/admin/survei'
      path: '/survei'
      fullPath: '/admin/survei'
      preLoaderRoute: typeof AuthenticatedAdminSurveiRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/surat': {
      id: '/_authenticated/admin/surat'
      path: '/surat'
      fullPath: '/admin/surat'
      preLoaderRoute: typeof AuthenticatedAdminSuratRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/support': {
      id: '/_authenticated/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AuthenticatedAdminSupportRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/statistik': {
      id: '/_authenticated/admin/statistik'
      path: '/statistik'
      fullPath: '/admin/statistik'
      preLoaderRoute: typeof AuthenticatedAdminStatistikRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/simpanan': {
      id: '/_authenticated/admin/simpanan'
      path: '/simpanan'
      fullPath: '/admin/simpanan'
      preLoaderRoute: typeof AuthenticatedAdminSimpananRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/shu': {
      id: '/_authenticated/admin/shu'
      path: '/shu'
      fullPath: '/admin/shu'
      preLoaderRoute: typeof AuthenticatedAdminShuRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/seller-verify': {
      id: '/_authenticated/admin/seller-verify'
      path: '/seller-verify'
      fullPath: '/admin/seller-verify'
      preLoaderRoute: typeof AuthenticatedAdminSellerVerifyRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/role': {
      id: '/_authenticated/admin/role'
      path: '/role'
      fullPath: '/admin/role'
      preLoaderRoute: typeof AuthenticatedAdminRoleRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/rekonsiliasi': {
      id: '/_authenticated/admin/rekonsiliasi'
      path: '/rekonsiliasi'
      fullPath: '/admin/rekonsiliasi'
      preLoaderRoute: typeof AuthenticatedAdminRekonsiliasiRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/rapb': {
      id: '/_authenticated/admin/rapb'
      path: '/rapb'
      fullPath: '/admin/rapb'
      preLoaderRoute: typeof AuthenticatedAdminRapbRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/qris': {
      id: '/_authenticated/admin/qris'
      path: '/qris'
      fullPath: '/admin/qris'
      preLoaderRoute: typeof AuthenticatedAdminQrisRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/pinjaman': {
      id: '/_authenticated/admin/pinjaman'
      path: '/pinjaman'
      fullPath: '/admin/pinjaman'
      preLoaderRoute: typeof AuthenticatedAdminPinjamanRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/penjamin': {
      id: '/_authenticated/admin/penjamin'
      path: '/penjamin'
      fullPath: '/admin/penjamin'
      preLoaderRoute: typeof AuthenticatedAdminPenjaminRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/pengaturan': {
      id: '/_authenticated/admin/pengaturan'
      path: '/pengaturan'
      fullPath: '/admin/pengaturan'
      preLoaderRoute: typeof AuthenticatedAdminPengaturanRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/penagihan': {
      id: '/_authenticated/admin/penagihan'
      path: '/penagihan'
      fullPath: '/admin/penagihan'
      preLoaderRoute: typeof AuthenticatedAdminPenagihanRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/opex': {
      id: '/_authenticated/admin/opex'
      path: '/opex'
      fullPath: '/admin/opex'
      preLoaderRoute: typeof AuthenticatedAdminOpexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/notifikasi-wa': {
      id: '/_authenticated/admin/notifikasi-wa'
      path: '/notifikasi-wa'
      fullPath: '/admin/notifikasi-wa'
      preLoaderRoute: typeof AuthenticatedAdminNotifikasiWaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/marketplace': {
      id: '/_authenticated/admin/marketplace'
      path: '/marketplace'
      fullPath: '/admin/marketplace'
      preLoaderRoute: typeof AuthenticatedAdminMarketplaceRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/lowongan': {
      id: '/_authenticated/admin/lowongan'
      path: '/lowongan'
      fullPath: '/admin/lowongan'
      preLoaderRoute: typeof AuthenticatedAdminLowonganRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/laporan-sak': {
      id: '/_authenticated/admin/laporan-sak'
      path: '/laporan-sak'
      fullPath: '/admin/laporan-sak'
      preLoaderRoute: typeof AuthenticatedAdminLaporanSakRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/laporan-rat': {
      id: '/_authenticated/admin/laporan-rat'
      path: '/laporan-rat'
      fullPath: '/admin/laporan-rat'
      preLoaderRoute: typeof AuthenticatedAdminLaporanRatRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/laporan': {
      id: '/_authenticated/admin/laporan'
      path: '/laporan'
      fullPath: '/admin/laporan'
      preLoaderRoute: typeof AuthenticatedAdminLaporanRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/kupon': {
      id: '/_authenticated/admin/kupon'
      path: '/kupon'
      fullPath: '/admin/kupon'
      preLoaderRoute: typeof AuthenticatedAdminKuponRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/komplain': {
      id: '/_authenticated/admin/komplain'
      path: '/komplain'
      fullPath: '/admin/komplain'
      preLoaderRoute: typeof AuthenticatedAdminKomplainRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/fee': {
      id: '/_authenticated/admin/fee'
      path: '/fee'
      fullPath: '/admin/fee'
      preLoaderRoute: typeof AuthenticatedAdminFeeRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/escrow': {
      id: '/_authenticated/admin/escrow'
      path: '/escrow'
      fullPath: '/admin/escrow'
      preLoaderRoute: typeof AuthenticatedAdminEscrowRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/dana-cadangan': {
      id: '/_authenticated/admin/dana-cadangan'
      path: '/dana-cadangan'
      fullPath: '/admin/dana-cadangan'
      preLoaderRoute: typeof AuthenticatedAdminDanaCadanganRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/buku-kas': {
      id: '/_authenticated/admin/buku-kas'
      path: '/buku-kas'
      fullPath: '/admin/buku-kas'
      preLoaderRoute: typeof AuthenticatedAdminBukuKasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/buku-besar': {
      id: '/_authenticated/admin/buku-besar'
      path: '/buku-besar'
      fullPath: '/admin/buku-besar'
      preLoaderRoute: typeof AuthenticatedAdminBukuBesarRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/berita': {
      id: '/_authenticated/admin/berita'
      path: '/berita'
      fullPath: '/admin/berita'
      preLoaderRoute: typeof AuthenticatedAdminBeritaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/backup': {
      id: '/_authenticated/admin/backup'
      path: '/backup'
      fullPath: '/admin/backup'
      preLoaderRoute: typeof AuthenticatedAdminBackupRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/aset': {
      id: '/_authenticated/admin/aset'
      path: '/aset'
      fullPath: '/admin/aset'
      preLoaderRoute: typeof AuthenticatedAdminAsetRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/arsip-transaksi': {
      id: '/_authenticated/admin/arsip-transaksi'
      path: '/arsip-transaksi'
      fullPath: '/admin/arsip-transaksi'
      preLoaderRoute: typeof AuthenticatedAdminArsipTransaksiRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/approval': {
      id: '/_authenticated/admin/approval'
      path: '/approval'
      fullPath: '/admin/approval'
      preLoaderRoute: typeof AuthenticatedAdminApprovalRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/angsuran': {
      id: '/_authenticated/admin/angsuran'
      path: '/angsuran'
      fullPath: '/admin/angsuran'
      preLoaderRoute: typeof AuthenticatedAdminAngsuranRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/anggota': {
      id: '/_authenticated/admin/anggota'
      path: '/anggota'
      fullPath: '/admin/anggota'
      preLoaderRoute: typeof AuthenticatedAdminAnggotaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/analitik': {
      id: '/_authenticated/admin/analitik'
      path: '/analitik'
      fullPath: '/admin/analitik'
      preLoaderRoute: typeof AuthenticatedAdminAnalitikRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/aktivitas': {
      id: '/_authenticated/admin/aktivitas'
      path: '/aktivitas'
      fullPath: '/admin/aktivitas'
      preLoaderRoute: typeof AuthenticatedAdminAktivitasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/akad': {
      id: '/_authenticated/admin/akad'
      path: '/akad'
      fullPath: '/admin/akad'
      preLoaderRoute: typeof AuthenticatedAdminAkadRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/hooks/daily-reminders': {
      id: '/api/public/hooks/daily-reminders'
      path: '/api/public/hooks/daily-reminders'
      fullPath: '/api/public/hooks/daily-reminders'
      preLoaderRoute: typeof ApiPublicHooksDailyRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/auto-release-escrow': {
      id: '/api/public/hooks/auto-release-escrow'
      path: '/api/public/hooks/auto-release-escrow'
      fullPath: '/api/public/hooks/auto-release-escrow'
      preLoaderRoute: typeof ApiPublicHooksAutoReleaseEscrowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/auto-debet-wajib': {
      id: '/api/public/hooks/auto-debet-wajib'
      path: '/api/public/hooks/auto-debet-wajib'
      fullPath: '/api/public/hooks/auto-debet-wajib'
      preLoaderRoute: typeof ApiPublicHooksAutoDebetWajibRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/accrue-fees': {
      id: '/api/public/hooks/accrue-fees'
      path: '/api/public/hooks/accrue-fees'
      fullPath: '/api/public/hooks/accrue-fees'
      preLoaderRoute: typeof ApiPublicHooksAccrueFeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/sekolah/pengadaan/$id': {
      id: '/_authenticated/sekolah/pengadaan/$id'
      path: '/$id'
      fullPath: '/sekolah/pengadaan/$id'
      preLoaderRoute: typeof AuthenticatedSekolahPengadaanIdRouteImport
      parentRoute: typeof AuthenticatedSekolahPengadaanRoute
    }
    '/_authenticated/gereja/pengadaan/$id': {
      id: '/_authenticated/gereja/pengadaan/$id'
      path: '/$id'
      fullPath: '/gereja/pengadaan/$id'
      preLoaderRoute: typeof AuthenticatedGerejaPengadaanIdRouteImport
      parentRoute: typeof AuthenticatedGerejaPengadaanRoute
    }
    '/_authenticated/admin/sekolah/pengadaan': {
      id: '/_authenticated/admin/sekolah/pengadaan'
      path: '/sekolah/pengadaan'
      fullPath: '/admin/sekolah/pengadaan'
      preLoaderRoute: typeof AuthenticatedAdminSekolahPengadaanRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/gereja/pengadaan': {
      id: '/_authenticated/admin/gereja/pengadaan'
      path: '/gereja/pengadaan'
      fullPath: '/admin/gereja/pengadaan'
      preLoaderRoute: typeof AuthenticatedAdminGerejaPengadaanRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAkadRoute: typeof AuthenticatedAdminAkadRoute
  AuthenticatedAdminAktivitasRoute: typeof AuthenticatedAdminAktivitasRoute
  AuthenticatedAdminAnalitikRoute: typeof AuthenticatedAdminAnalitikRoute
  AuthenticatedAdminAnggotaRoute: typeof AuthenticatedAdminAnggotaRoute
  AuthenticatedAdminAngsuranRoute: typeof AuthenticatedAdminAngsuranRoute
  AuthenticatedAdminApprovalRoute: typeof AuthenticatedAdminApprovalRoute
  AuthenticatedAdminArsipTransaksiRoute: typeof AuthenticatedAdminArsipTransaksiRoute
  AuthenticatedAdminAsetRoute: typeof AuthenticatedAdminAsetRoute
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminBackupRoute: typeof AuthenticatedAdminBackupRoute
  AuthenticatedAdminBeritaRoute: typeof AuthenticatedAdminBeritaRoute
  AuthenticatedAdminBukuBesarRoute: typeof AuthenticatedAdminBukuBesarRoute
  AuthenticatedAdminBukuKasRoute: typeof AuthenticatedAdminBukuKasRoute
  AuthenticatedAdminDanaCadanganRoute: typeof AuthenticatedAdminDanaCadanganRoute
  AuthenticatedAdminEscrowRoute: typeof AuthenticatedAdminEscrowRoute
  AuthenticatedAdminFeeRoute: typeof AuthenticatedAdminFeeRoute
  AuthenticatedAdminKomplainRoute: typeof AuthenticatedAdminKomplainRoute
  AuthenticatedAdminKuponRoute: typeof AuthenticatedAdminKuponRoute
  AuthenticatedAdminLaporanRoute: typeof AuthenticatedAdminLaporanRoute
  AuthenticatedAdminLaporanRatRoute: typeof AuthenticatedAdminLaporanRatRoute
  AuthenticatedAdminLaporanSakRoute: typeof AuthenticatedAdminLaporanSakRoute
  AuthenticatedAdminLowonganRoute: typeof AuthenticatedAdminLowonganRoute
  AuthenticatedAdminMarketplaceRoute: typeof AuthenticatedAdminMarketplaceRoute
  AuthenticatedAdminNotifikasiWaRoute: typeof AuthenticatedAdminNotifikasiWaRoute
  AuthenticatedAdminOpexRoute: typeof AuthenticatedAdminOpexRoute
  AuthenticatedAdminPenagihanRoute: typeof AuthenticatedAdminPenagihanRoute
  AuthenticatedAdminPengaturanRoute: typeof AuthenticatedAdminPengaturanRoute
  AuthenticatedAdminPenjaminRoute: typeof AuthenticatedAdminPenjaminRoute
  AuthenticatedAdminPinjamanRoute: typeof AuthenticatedAdminPinjamanRoute
  AuthenticatedAdminQrisRoute: typeof AuthenticatedAdminQrisRoute
  AuthenticatedAdminRapbRoute: typeof AuthenticatedAdminRapbRoute
  AuthenticatedAdminRekonsiliasiRoute: typeof AuthenticatedAdminRekonsiliasiRoute
  AuthenticatedAdminRoleRoute: typeof AuthenticatedAdminRoleRoute
  AuthenticatedAdminSellerVerifyRoute: typeof AuthenticatedAdminSellerVerifyRoute
  AuthenticatedAdminShuRoute: typeof AuthenticatedAdminShuRoute
  AuthenticatedAdminSimpananRoute: typeof AuthenticatedAdminSimpananRoute
  AuthenticatedAdminStatistikRoute: typeof AuthenticatedAdminStatistikRoute
  AuthenticatedAdminSupportRoute: typeof AuthenticatedAdminSupportRoute
  AuthenticatedAdminSuratRoute: typeof AuthenticatedAdminSuratRoute
  AuthenticatedAdminSurveiRoute: typeof AuthenticatedAdminSurveiRoute
  AuthenticatedAdminTabunganBerjangkaRoute: typeof AuthenticatedAdminTabunganBerjangkaRoute
  AuthenticatedAdminVerifikasiPinjamanRoute: typeof AuthenticatedAdminVerifikasiPinjamanRoute
  AuthenticatedAdminVotingRoute: typeof AuthenticatedAdminVotingRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminGerejaPengadaanRoute: typeof AuthenticatedAdminGerejaPengadaanRoute
  AuthenticatedAdminSekolahPengadaanRoute: typeof AuthenticatedAdminSekolahPengadaanRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAkadRoute: AuthenticatedAdminAkadRoute,
  AuthenticatedAdminAktivitasRoute: AuthenticatedAdminAktivitasRoute,
  AuthenticatedAdminAnalitikRoute: AuthenticatedAdminAnalitikRoute,
  AuthenticatedAdminAnggotaRoute: AuthenticatedAdminAnggotaRoute,
  AuthenticatedAdminAngsuranRoute: AuthenticatedAdminAngsuranRoute,
  AuthenticatedAdminApprovalRoute: AuthenticatedAdminApprovalRoute,
  AuthenticatedAdminArsipTransaksiRoute: AuthenticatedAdminArsipTransaksiRoute,
  AuthenticatedAdminAsetRoute: AuthenticatedAdminAsetRoute,
  AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
  AuthenticatedAdminBackupRoute: AuthenticatedAdminBackupRoute,
  AuthenticatedAdminBeritaRoute: AuthenticatedAdminBeritaRoute,
  AuthenticatedAdminBukuBesarRoute: AuthenticatedAdminBukuBesarRoute,
  AuthenticatedAdminBukuKasRoute: AuthenticatedAdminBukuKasRoute,
  AuthenticatedAdminDanaCadanganRoute: AuthenticatedAdminDanaCadanganRoute,
  AuthenticatedAdminEscrowRoute: AuthenticatedAdminEscrowRoute,
  AuthenticatedAdminFeeRoute: AuthenticatedAdminFeeRoute,
  AuthenticatedAdminKomplainRoute: AuthenticatedAdminKomplainRoute,
  AuthenticatedAdminKuponRoute: AuthenticatedAdminKuponRoute,
  AuthenticatedAdminLaporanRoute: AuthenticatedAdminLaporanRoute,
  AuthenticatedAdminLaporanRatRoute: AuthenticatedAdminLaporanRatRoute,
  AuthenticatedAdminLaporanSakRoute: AuthenticatedAdminLaporanSakRoute,
  AuthenticatedAdminLowonganRoute: AuthenticatedAdminLowonganRoute,
  AuthenticatedAdminMarketplaceRoute: AuthenticatedAdminMarketplaceRoute,
  AuthenticatedAdminNotifikasiWaRoute: AuthenticatedAdminNotifikasiWaRoute,
  AuthenticatedAdminOpexRoute: AuthenticatedAdminOpexRoute,
  AuthenticatedAdminPenagihanRoute: AuthenticatedAdminPenagihanRoute,
  AuthenticatedAdminPengaturanRoute: AuthenticatedAdminPengaturanRoute,
  AuthenticatedAdminPenjaminRoute: AuthenticatedAdminPenjaminRoute,
  AuthenticatedAdminPinjamanRoute: AuthenticatedAdminPinjamanRoute,
  AuthenticatedAdminQrisRoute: AuthenticatedAdminQrisRoute,
  AuthenticatedAdminRapbRoute: AuthenticatedAdminRapbRoute,
  AuthenticatedAdminRekonsiliasiRoute: AuthenticatedAdminRekonsiliasiRoute,
  AuthenticatedAdminRoleRoute: AuthenticatedAdminRoleRoute,
  AuthenticatedAdminSellerVerifyRoute: AuthenticatedAdminSellerVerifyRoute,
  AuthenticatedAdminShuRoute: AuthenticatedAdminShuRoute,
  AuthenticatedAdminSimpananRoute: AuthenticatedAdminSimpananRoute,
  AuthenticatedAdminStatistikRoute: AuthenticatedAdminStatistikRoute,
  AuthenticatedAdminSupportRoute: AuthenticatedAdminSupportRoute,
  AuthenticatedAdminSuratRoute: AuthenticatedAdminSuratRoute,
  AuthenticatedAdminSurveiRoute: AuthenticatedAdminSurveiRoute,
  AuthenticatedAdminTabunganBerjangkaRoute:
    AuthenticatedAdminTabunganBerjangkaRoute,
  AuthenticatedAdminVerifikasiPinjamanRoute:
    AuthenticatedAdminVerifikasiPinjamanRoute,
  AuthenticatedAdminVotingRoute: AuthenticatedAdminVotingRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminGerejaPengadaanRoute:
    AuthenticatedAdminGerejaPengadaanRoute,
  AuthenticatedAdminSekolahPengadaanRoute:
    AuthenticatedAdminSekolahPengadaanRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedGerejaPengadaanRouteChildren {
  AuthenticatedGerejaPengadaanIdRoute: typeof AuthenticatedGerejaPengadaanIdRoute
}

const AuthenticatedGerejaPengadaanRouteChildren: AuthenticatedGerejaPengadaanRouteChildren =
  {
    AuthenticatedGerejaPengadaanIdRoute: AuthenticatedGerejaPengadaanIdRoute,
  }

const AuthenticatedGerejaPengadaanRouteWithChildren =
  AuthenticatedGerejaPengadaanRoute._addFileChildren(
    AuthenticatedGerejaPengadaanRouteChildren,
  )

interface AuthenticatedSekolahPengadaanRouteChildren {
  AuthenticatedSekolahPengadaanIdRoute: typeof AuthenticatedSekolahPengadaanIdRoute
}

const AuthenticatedSekolahPengadaanRouteChildren: AuthenticatedSekolahPengadaanRouteChildren =
  {
    AuthenticatedSekolahPengadaanIdRoute: AuthenticatedSekolahPengadaanIdRoute,
  }

const AuthenticatedSekolahPengadaanRouteWithChildren =
  AuthenticatedSekolahPengadaanRoute._addFileChildren(
    AuthenticatedSekolahPengadaanRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAngsuranRoute: typeof AuthenticatedAngsuranRoute
  AuthenticatedApprovalRoute: typeof AuthenticatedApprovalRoute
  AuthenticatedBantuanRoute: typeof AuthenticatedBantuanRoute
  AuthenticatedBukuBesarRoute: typeof AuthenticatedBukuBesarRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDashboardBelanjaRoute: typeof AuthenticatedDashboardBelanjaRoute
  AuthenticatedDokumenRoute: typeof AuthenticatedDokumenRoute
  AuthenticatedFavoritRoute: typeof AuthenticatedFavoritRoute
  AuthenticatedKalkulatorRoute: typeof AuthenticatedKalkulatorRoute
  AuthenticatedLowonganRoute: typeof AuthenticatedLowonganRoute
  AuthenticatedMarketplaceSayaRoute: typeof AuthenticatedMarketplaceSayaRoute
  AuthenticatedPenjaminRoute: typeof AuthenticatedPenjaminRoute
  AuthenticatedPinjamanRoute: typeof AuthenticatedPinjamanRoute
  AuthenticatedProfilRoute: typeof AuthenticatedProfilRoute
  AuthenticatedRapatRoute: typeof AuthenticatedRapatRoute
  AuthenticatedRiwayatRoute: typeof AuthenticatedRiwayatRoute
  AuthenticatedSaldoRoute: typeof AuthenticatedSaldoRoute
  AuthenticatedShuRoute: typeof AuthenticatedShuRoute
  AuthenticatedSimpananRoute: typeof AuthenticatedSimpananRoute
  AuthenticatedSurveiRoute: typeof AuthenticatedSurveiRoute
  AuthenticatedTabunganBerjangkaRoute: typeof AuthenticatedTabunganBerjangkaRoute
  AuthenticatedTransaksiSayaRoute: typeof AuthenticatedTransaksiSayaRoute
  AuthenticatedVotingRoute: typeof AuthenticatedVotingRoute
  AuthenticatedGerejaPengadaanRoute: typeof AuthenticatedGerejaPengadaanRouteWithChildren
  AuthenticatedSekolahPengadaanRoute: typeof AuthenticatedSekolahPengadaanRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAngsuranRoute: AuthenticatedAngsuranRoute,
  AuthenticatedApprovalRoute: AuthenticatedApprovalRoute,
  AuthenticatedBantuanRoute: AuthenticatedBantuanRoute,
  AuthenticatedBukuBesarRoute: AuthenticatedBukuBesarRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDashboardBelanjaRoute: AuthenticatedDashboardBelanjaRoute,
  AuthenticatedDokumenRoute: AuthenticatedDokumenRoute,
  AuthenticatedFavoritRoute: AuthenticatedFavoritRoute,
  AuthenticatedKalkulatorRoute: AuthenticatedKalkulatorRoute,
  AuthenticatedLowonganRoute: AuthenticatedLowonganRoute,
  AuthenticatedMarketplaceSayaRoute: AuthenticatedMarketplaceSayaRoute,
  AuthenticatedPenjaminRoute: AuthenticatedPenjaminRoute,
  AuthenticatedPinjamanRoute: AuthenticatedPinjamanRoute,
  AuthenticatedProfilRoute: AuthenticatedProfilRoute,
  AuthenticatedRapatRoute: AuthenticatedRapatRoute,
  AuthenticatedRiwayatRoute: AuthenticatedRiwayatRoute,
  AuthenticatedSaldoRoute: AuthenticatedSaldoRoute,
  AuthenticatedShuRoute: AuthenticatedShuRoute,
  AuthenticatedSimpananRoute: AuthenticatedSimpananRoute,
  AuthenticatedSurveiRoute: AuthenticatedSurveiRoute,
  AuthenticatedTabunganBerjangkaRoute: AuthenticatedTabunganBerjangkaRoute,
  AuthenticatedTransaksiSayaRoute: AuthenticatedTransaksiSayaRoute,
  AuthenticatedVotingRoute: AuthenticatedVotingRoute,
  AuthenticatedGerejaPengadaanRoute:
    AuthenticatedGerejaPengadaanRouteWithChildren,
  AuthenticatedSekolahPengadaanRoute:
    AuthenticatedSekolahPengadaanRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface BeritaRouteChildren {
  BeritaSlugRoute: typeof BeritaSlugRoute
  BeritaIndexRoute: typeof BeritaIndexRoute
}

const BeritaRouteChildren: BeritaRouteChildren = {
  BeritaSlugRoute: BeritaSlugRoute,
  BeritaIndexRoute: BeritaIndexRoute,
}

const BeritaRouteWithChildren =
  BeritaRoute._addFileChildren(BeritaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  BeritaRoute: BeritaRouteWithChildren,
  DaftarAnggotaRoute: DaftarAnggotaRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TentangRoute: TentangRoute,
  VerifyRoute: VerifyRoute,
  MarketplaceCheckoutRoute: MarketplaceCheckoutRoute,
  MarketplaceKeranjangRoute: MarketplaceKeranjangRoute,
  MarketplaceIndexRoute: MarketplaceIndexRoute,
  MarketplaceProdukIdRoute: MarketplaceProdukIdRoute,
  MarketplaceTokoSlugRoute: MarketplaceTokoSlugRoute,
  ApiPublicHooksAccrueFeesRoute: ApiPublicHooksAccrueFeesRoute,
  ApiPublicHooksAutoDebetWajibRoute: ApiPublicHooksAutoDebetWajibRoute,
  ApiPublicHooksAutoReleaseEscrowRoute: ApiPublicHooksAutoReleaseEscrowRoute,
  ApiPublicHooksDailyRemindersRoute: ApiPublicHooksDailyRemindersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
