/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSimpananRouteImport } from './routes/_authenticated/simpanan'
import { Route as AuthenticatedPinjamanRouteImport } from './routes/_authenticated/pinjaman'
import { Route as AuthenticatedKalkulatorRouteImport } from './routes/_authenticated/kalkulator'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAngsuranRouteImport } from './routes/_authenticated/angsuran'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminSimpananRouteImport } from './routes/_authenticated/admin.simpanan'
import { Route as AuthenticatedAdminPinjamanRouteImport } from './routes/_authenticated/admin.pinjaman'
import { Route as AuthenticatedAdminAnggotaRouteImport } from './routes/_authenticated/admin.anggota'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSimpananRoute = AuthenticatedSimpananRouteImport.update({
  id: '/simpanan',
  path: '/simpanan',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPinjamanRoute = AuthenticatedPinjamanRouteImport.update({
  id: '/pinjaman',
  path: '/pinjaman',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedKalkulatorRoute = AuthenticatedKalkulatorRouteImport.update({
  id: '/kalkulator',
  path: '/kalkulator',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAngsuranRoute = AuthenticatedAngsuranRouteImport.update({
  id: '/angsuran',
  path: '/angsuran',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminSimpananRoute =
  AuthenticatedAdminSimpananRouteImport.update({
    id: '/simpanan',
    path: '/simpanan',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPinjamanRoute =
  AuthenticatedAdminPinjamanRouteImport.update({
    id: '/pinjaman',
    path: '/pinjaman',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAnggotaRoute =
  AuthenticatedAdminAnggotaRouteImport.update({
    id: '/anggota',
    path: '/anggota',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/angsuran': typeof AuthenticatedAngsuranRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/kalkulator': typeof AuthenticatedKalkulatorRoute
  '/pinjaman': typeof AuthenticatedPinjamanRoute
  '/simpanan': typeof AuthenticatedSimpananRoute
  '/admin/anggota': typeof AuthenticatedAdminAnggotaRoute
  '/admin/pinjaman': typeof AuthenticatedAdminPinjamanRoute
  '/admin/simpanan': typeof AuthenticatedAdminSimpananRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/angsuran': typeof AuthenticatedAngsuranRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/kalkulator': typeof AuthenticatedKalkulatorRoute
  '/pinjaman': typeof AuthenticatedPinjamanRoute
  '/simpanan': typeof AuthenticatedSimpananRoute
  '/admin/anggota': typeof AuthenticatedAdminAnggotaRoute
  '/admin/pinjaman': typeof AuthenticatedAdminPinjamanRoute
  '/admin/simpanan': typeof AuthenticatedAdminSimpananRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/angsuran': typeof AuthenticatedAngsuranRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/kalkulator': typeof AuthenticatedKalkulatorRoute
  '/_authenticated/pinjaman': typeof AuthenticatedPinjamanRoute
  '/_authenticated/simpanan': typeof AuthenticatedSimpananRoute
  '/_authenticated/admin/anggota': typeof AuthenticatedAdminAnggotaRoute
  '/_authenticated/admin/pinjaman': typeof AuthenticatedAdminPinjamanRoute
  '/_authenticated/admin/simpanan': typeof AuthenticatedAdminSimpananRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/angsuran'
    | '/dashboard'
    | '/kalkulator'
    | '/pinjaman'
    | '/simpanan'
    | '/admin/anggota'
    | '/admin/pinjaman'
    | '/admin/simpanan'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/angsuran'
    | '/dashboard'
    | '/kalkulator'
    | '/pinjaman'
    | '/simpanan'
    | '/admin/anggota'
    | '/admin/pinjaman'
    | '/admin/simpanan'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/angsuran'
    | '/_authenticated/dashboard'
    | '/_authenticated/kalkulator'
    | '/_authenticated/pinjaman'
    | '/_authenticated/simpanan'
    | '/_authenticated/admin/anggota'
    | '/_authenticated/admin/pinjaman'
    | '/_authenticated/admin/simpanan'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/simpanan': {
      id: '/_authenticated/simpanan'
      path: '/simpanan'
      fullPath: '/simpanan'
      preLoaderRoute: typeof AuthenticatedSimpananRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pinjaman': {
      id: '/_authenticated/pinjaman'
      path: '/pinjaman'
      fullPath: '/pinjaman'
      preLoaderRoute: typeof AuthenticatedPinjamanRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/kalkulator': {
      id: '/_authenticated/kalkulator'
      path: '/kalkulator'
      fullPath: '/kalkulator'
      preLoaderRoute: typeof AuthenticatedKalkulatorRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/angsuran': {
      id: '/_authenticated/angsuran'
      path: '/angsuran'
      fullPath: '/angsuran'
      preLoaderRoute: typeof AuthenticatedAngsuranRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/simpanan': {
      id: '/_authenticated/admin/simpanan'
      path: '/simpanan'
      fullPath: '/admin/simpanan'
      preLoaderRoute: typeof AuthenticatedAdminSimpananRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/pinjaman': {
      id: '/_authenticated/admin/pinjaman'
      path: '/pinjaman'
      fullPath: '/admin/pinjaman'
      preLoaderRoute: typeof AuthenticatedAdminPinjamanRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/anggota': {
      id: '/_authenticated/admin/anggota'
      path: '/anggota'
      fullPath: '/admin/anggota'
      preLoaderRoute: typeof AuthenticatedAdminAnggotaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAnggotaRoute: typeof AuthenticatedAdminAnggotaRoute
  AuthenticatedAdminPinjamanRoute: typeof AuthenticatedAdminPinjamanRoute
  AuthenticatedAdminSimpananRoute: typeof AuthenticatedAdminSimpananRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAnggotaRoute: AuthenticatedAdminAnggotaRoute,
  AuthenticatedAdminPinjamanRoute: AuthenticatedAdminPinjamanRoute,
  AuthenticatedAdminSimpananRoute: AuthenticatedAdminSimpananRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAngsuranRoute: typeof AuthenticatedAngsuranRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedKalkulatorRoute: typeof AuthenticatedKalkulatorRoute
  AuthenticatedPinjamanRoute: typeof AuthenticatedPinjamanRoute
  AuthenticatedSimpananRoute: typeof AuthenticatedSimpananRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAngsuranRoute: AuthenticatedAngsuranRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedKalkulatorRoute: AuthenticatedKalkulatorRoute,
  AuthenticatedPinjamanRoute: AuthenticatedPinjamanRoute,
  AuthenticatedSimpananRoute: AuthenticatedSimpananRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
