REVOKE EXECUTE ON ALL FUNCTIONS IN SCHEMA public FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO service_role;
GRANT EXECUTE ON FUNCTION public.has_role(uuid, app_role) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.is_pengurus(uuid) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.is_active_seller(uuid) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.is_finance(uuid) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.is_ketua(uuid) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.is_leader(uuid) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.is_secretary(uuid) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.is_church_requester(uuid) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.is_school_requester(uuid) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.is_sa_identity(text, text) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.normalize_phone_id(text) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.get_email_by_phone(text) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.get_public_lowongan(integer) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.get_featured_products(integer) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.get_top_products(integer) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.get_public_pengurus() TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.get_public_koperasi_stats() TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.get_public_recent_activity(integer) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.get_public_tentang() TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.increment_product_view(uuid) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.gen_qris_invoice_no() TO authenticated;
GRANT EXECUTE ON FUNCTION public.ensure_my_profile() TO authenticated;
GRANT EXECUTE ON FUNCTION public.ensure_super_admin() TO authenticated;
GRANT EXECUTE ON FUNCTION public.act_on_guarantor_request(uuid, text, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.approve_member(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.cast_rat_vote(uuid, jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.compute_asset_depreciation(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_fee_breakdown() TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_jurnal_umum(date, date) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_marketplace_admin_stats() TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_marketplace_stats() TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_member_ledger(uuid, date, date) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_opex_budget_status(uuid, integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_rapb_realisasi(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_rat_voting_result(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_user_marketplace_activity(uuid, integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.mp_confirm_received(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.mp_file_complaint(uuid, text, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.mp_process_withdrawal(uuid, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.mp_reject_withdrawal(uuid, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.mp_resolve_complaint(uuid, text, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.mp_review_loan_verification(uuid, text, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.mp_set_store_status(uuid, store_status, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.mp_ship(uuid, text, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.mp_upload_bukti(uuid, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.mp_verify_payment(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.qris_mark_success(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.sync_collection_cases() TO authenticated;
GRANT EXECUTE ON FUNCTION public.validate_guarantor(uuid, numeric) TO authenticated;